### ISSUE TITLE
Improve readability of JSON files

### ISSUE THREAD

**Issue by lmars** [theupdateframework/go-tuf#12]
All JSON files should be formatted with `MarshalIndent` and have a trailing newline at the end.

**Comment by lmars** [comment]
The change to indent the JSON (#21) was reverted, see [this commit](https://github.com/flynn/go-tuf/commit/898fa10a2af936c1295c9c57eed95bdc1615048b).

**Comment by nbering** [comment]
The Update Framework specification requires the use of "canonical JSON", which does not allow for whitespace at all. Perhaps reasonable to close this issue since it violates specification?

https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats
http://wiki.laptop.org/go/Canonical_JSON

**Comment by zwass** [comment]
Agreed, @lmars this issue looks like it should be closed given that it would violate the Canonical JSON spec linked by @nbering.
