### ISSUE TITLE
Remove root pinning in snapshot

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#203]
TUF specification does not require root pinning in the snapshot file https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#file-formats-snapshotjson--file-formats-snapshot

Remove https://github.com/theupdateframework/go-tuf/blob/5573c9c8694deb40c802a5d9d62eed5c1c47041a/repo.go#L31

c/f https://twitter.com/trishankkarthik/status/1479894513627930633

**Comment by zwass** [comment]
`go-tuf` now generates a repository that always causes warnings (which cannot be silenced due to use of `fmt.Println`) because of this: https://github.com/theupdateframework/go-tuf/blob/master/client/client.go#L196

Can we either quickly move to fix the output so that it's internally consistent, or roll back that log statement?

We keep hearing from folks who are concerned about this, similar to the Twitter thread: https://github.com/fleetdm/fleet/issues/3699

Is it simply a matter of removing `root.json` from that list?

**Comment by asraa** [comment]
> Is it simply a matter of removing root.json from that list?

Yes! It's handled in https://github.com/theupdateframework/go-tuf/pull/198

@ethan-lowman-dd do you mind if we split that part out?

**Comment by ethan-lowman-dd** [comment]
@asraa Should we try to merge all of #198 or do you want to separate out just part of it?

**Comment by asraa** [comment]
I think the PR stands alone pretty easily (I forgot that #8 means it doesn't need to be #8 merged). Taking another review on it.

**Comment by trishankatdatadog** [comment]
> c/f https://twitter.com/trishankkarthik/status/1479894513627930633

Good lords, how many times do you get a tweet cited in an issue... 😅

**Comment by zwass** [comment]
Looks like this can be closed now that #198 is merged? Thanks y'all!
