### ISSUE TITLE
Possible bug in `isTargetInPathPattern`

### ISSUE THREAD

**Issue by adityasaky** [theupdateframework/go-tuf#590]
The implementation for this helper is here: https://github.com/theupdateframework/go-tuf/blob/9d57731720841af71c5f70d590e531136e0b025d/metadata/metadata.go#L535-L554

If I'm reading this right, this helper is responsible for identifying if a delegation pattern matches a target path. However, it incorrectly says a pattern like `foo/*` does not match `foo/bar/foobar.txt`. The same pattern does correctly match `foo/foobar.txt`. This is because both the pattern and the target path are split into their components using the separator, and if they don't have the same number of components, the helper returns false.

See: https://go.dev/play/p/6Mswjm_fM-4

**Comment by adityasaky** [comment]
After a discussion with @rdimitrov, @trishankatdatadog, and @mnm678, this is not an issue but likely deserving of some further clarification in the docs and in the TUF spec. See: https://theupdateframework.github.io/specification/latest/index.html#file-formats-targets for a description of how patterns work.

I'm going to submit some updated text to the specification, but this issue can be closed. :)

**Comment by trishankatdatadog** [comment]
IOW, the current behaviour is intended to be a feature not a bug in TUF 🙂

**Comment by brettinternet** [comment]
This was difficult to ascertain since the TUF examples I find don't demonstrate deeply nesting paths.

Here's a link to the path pattern spec: https://theupdateframework.github.io/specification/latest/index.html#pathpattern

To anyone wanting to test the Go client pattern matching, you can use: https://github.com/theupdateframework/go-tuf/blob/master/metadata/metadata.go#L547-L565

Playground: https://go.dev/play/p/Absw9VMixbD

**Comment by rdimitrov** [comment]
Thanks for sharing these @brettinternet 🙌 BTW if you have some cycles and are interested it would be much appreciated if you want to add such a use case to the examples 👍
